// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqJaYIRIXGffLdqWPvqtUd2YuX-70aYNs',
    appId: '1:598480858194:web:05864fd2fa8372a878838b',
    messagingSenderId: '598480858194',
    projectId: 'local-loop-a4840',
    authDomain: 'local-loop-a4840.firebaseapp.com',
    storageBucket: 'local-loop-a4840.firebasestorage.app',
    measurementId: 'G-2SJ64DF807',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVXMpUasZcOEEBXykTyny_OPhL_VWWqks',
    appId: '1:598480858194:android:04f0b294c4259dfc78838b',
    messagingSenderId: '598480858194',
    projectId: 'local-loop-a4840',
    storageBucket: 'local-loop-a4840.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaVYAlIptjCjRiYoZbYGeJXtjynfyyBfQ',
    appId: '1:598480858194:ios:fb9e4509c274fb6678838b',
    messagingSenderId: '598480858194',
    projectId: 'local-loop-a4840',
    storageBucket: 'local-loop-a4840.firebasestorage.app',
    iosBundleId: 'com.example.localLoop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaVYAlIptjCjRiYoZbYGeJXtjynfyyBfQ',
    appId: '1:598480858194:ios:fb9e4509c274fb6678838b',
    messagingSenderId: '598480858194',
    projectId: 'local-loop-a4840',
    storageBucket: 'local-loop-a4840.firebasestorage.app',
    iosBundleId: 'com.example.localLoop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqJaYIRIXGffLdqWPvqtUd2YuX-70aYNs',
    appId: '1:598480858194:web:fbccd141e067430678838b',
    messagingSenderId: '598480858194',
    projectId: 'local-loop-a4840',
    authDomain: 'local-loop-a4840.firebaseapp.com',
    storageBucket: 'local-loop-a4840.firebasestorage.app',
    measurementId: 'G-95BRF2H08V',
  );
}
